---
region: 'eu-west-2'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

source_policy_json: ""

acl: "private"

tags: "{}"

kms_key_arn: ""

access_log_bucket_arn: ""
access_log_object_key_prefix: ""

enable_mfa_delete: 'false'
enable_versioning: 'true'
enable_access_logging: 'false'
enable_bucket_key: 'false'
allow_destroy_when_objects_present: 'false'

public_access_block:
  block_public_acls: false
  block_public_policy: false
  ignore_public_acls: false
  restrict_public_buckets: false
