---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  encrypted_bucket_name: "infrablocks-encrypted-%{hiera('deployment_identifier')}"
  access_log_bucket_name: "infrablocks-access-log-%{hiera('deployment_identifier')}"
