---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  bucket_name: "infrablocks-encrypted-%{hiera('deployment_identifier')}"

  source_policy_document: "%{hiera('source_policy_document')}"

  acl: "%{hiera('acl')}"

  tags: "%{hiera('tags')}"

  kms_key_arn: "%{hiera('kms_key_arn')}"

  access_log_bucket_name: "%{hiera('access_log_bucket_name')}"
  access_log_object_key_prefix: "%{hiera('access_log_object_key_prefix')}"

  include_deny_unencrypted_inflight_operations_statement: "%{hiera('include_deny_unencrypted_inflight_operations_statement')}"
  include_deny_encryption_using_incorrect_algorithm_statement: "%{hiera('include_deny_encryption_using_incorrect_algorithm_statement')}"
  include_deny_encryption_using_incorrect_key_statement: "%{hiera('include_deny_encryption_using_incorrect_key_statement')}"

  enable_mfa_delete: "%{hiera('enable_mfa_delete')}"
  enable_versioning: "%{hiera('enable_versioning')}"
  enable_access_logging: "%{hiera('enable_access_logging')}"
  enable_bucket_key: "%{hiera('enable_bucket_key')}"
  allow_destroy_when_objects_present: "%{hiera('allow_destroy_when_objects_present')}"

  public_access_block: "%{hiera('public_access_block')}"
