---
configuration_directory: "%{cwd}/spec/unit/infra/prerequisites"
state_file: "%{cwd}/state/prerequisites.tfstate"
vars:
  region: "%{hiera('region')}"

  access_log_bucket_name: "infrablocks-access-%{hiera('deployment_identifier')}"
